src/Entity/Ue.php
<?php
/*
 * Copyright (c) 2021. | David Annebicque | IUT de Troyes  - All Rights Reserved
 * @file /Users/davidannebicque/htdocs/intranetV3/src/Entity/Ue.php
 * @author davidannebicque
 * @project intranetV3
 * @lastUpdate 06/06/2021 09:36
 */

namespace App\Entity;

use App\Entity\Traits\LifeCycleTrait;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UeRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Ue extends BaseEntity
{
    use LifeCycleTrait;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private string $libelle;

    /**
     *
     * @ORM\Column(type="integer")
     */
    private int $numeroUe = 1;

    /**
     *
     * @ORM\Column(type="float")
     */
    private float $coefficient = 1;

    /**
     *
     * @ORM\Column(type="float")
     */
    private float $nbEcts = 1;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Matiere", mappedBy="ue")
     */
    private Collection $matieres;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Semestre", inversedBy="ues")
     */
    private ?Semestre $semestre;

    /**
     * @ORM\Column(type="boolean")
     */
    private bool $actif = true;

    /**
     * @ORM\Column(type="boolean")
     */
    private bool $bonification = false;

    /**
     * @ORM\Column(type="string", length=15)
     */
    private string $codeElement;

    /**
     * @ORM\ManyToOne(targetEntity=ApcCompetence::class, inversedBy="ue")
     */
    private ?ApcCompetence $apcCompetence;

    /**
     * Ue constructor.
     */
    public function __construct(Semestre $semestre)
    {
        $this->matieres = new ArrayCollection();
        $this->semestre = $semestre;
    }

    public function getLibelle(): ?string
    {
        return $this->libelle;
    }

    public function setLibelle($libelle): void
    {
        $this->libelle = $libelle;
    }

    public function getNumeroUe(): int
    {
        return $this->numeroUe;
    }

    public function setNumeroUe(int $numeroUe): void
    {
        $this->numeroUe = $numeroUe;
    }

    public function getCoefficient(): float
    {
        return $this->coefficient;
    }

    public function setCoefficient(float $coefficient): void
    {
        $this->coefficient = $coefficient;
    }

    public function getNbEcts(): float
    {
        return $this->nbEcts;
    }

    public function setNbEcts(float $nbEcts): void
    {
        $this->nbEcts = $nbEcts;
    }

    public function getDiplome(): ?Diplome
    {
        if (null !== $this->semestre && null !== $this->semestre->getAnnee() && null !== $this->semestre->getAnnee()->getDiplome()) {
            return $this->semestre->getAnnee()->getDiplome();
        }

        return null;
    }

    /**
     * @return Collection|Matiere[]
     */
    public function getMatieres(): Collection
    {
        return $this->matieres;
    }

    public function addMatiere(Matiere $matiere): self
    {
        if (!$this->matieres->contains($matiere)) {
            $this->matieres[] = $matiere;
            $matiere->setUe($this);
        }

        return $this;
    }

    public function removeMatiere(Matiere $matiere): self
    {
        if ($this->matieres->contains($matiere)) {
            $this->matieres->removeElement($matiere);
            // set the owning side to null (unless already changed)
            if ($matiere->getUe() === $this) {
                $matiere->setUe(null);
            }
        }

        return $this;
    }

    public function getSemestre(): ?Semestre
    {
        return $this->semestre;
    }

    public function setSemestre(?Semestre $semestre): self
    {
        $this->semestre = $semestre;

        return $this;
    }

    public function getActif(): ?bool
    {
        return $this->actif;
    }

    public function setActif(bool $actif): self
    {
        $this->actif = $actif;

        return $this;
    }

    public function getDisplay(): string
    {
        return 'UE '.$this->getNumeroUe().' | '.$this->getLibelle();
    }

    public function getBonification(): ?bool
    {
        return $this->bonification;
    }

    public function setBonification(bool $bonification): self
    {
        $this->bonification = $bonification;

        return $this;
    }

    public function getCodeElement(): ?string
    {
        return $this->codeElement;
    }

    public function setCodeElement(string $codeElement): self
    {
        $this->codeElement = $codeElement;

        return $this;
    }

    public function getApcCompetence(): ?ApcCompetence
    {
        return $this->apcCompetence;
    }

    public function setApcCompetence(?ApcCompetence $apcCompetence): self
    {
        $this->apcCompetence = $apcCompetence;

        return $this;
    }
}

src/Controller/AdministrationController.php
<?php
/*
 * Copyright (c) 2021. | David Annebicque | IUT de Troyes  - All Rights Reserved
 * @file /Users/davidannebicque/htdocs/intranetV3/src/Controller/AdministrationController.php
 * @author davidannebicque
 * @project intranetV3
 * @lastUpdate 08/10/2021 07:01
 */

namespace App\Controller;

use App\Repository\ProjetPeriodeRepository;
use App\Repository\StagePeriodeRepository;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class AdministrationController.
 */
#[Route(path: '/administration')]
class AdministrationController extends BaseController
{
    #[Route(path: '/', name: 'administration_index')]
    public function index(
        StagePeriodeRepository $stagePeriodeRepository,
        ProjetPeriodeRepository $projetPeriodeRepository
    ): Response {
        $tperiodes = [];
        foreach ($this->dataUserSession->getDiplomes() as $diplome) {
            $periodes = $stagePeriodeRepository->findByDiplome($diplome, $diplome->getAnneeUniversitaire());
            foreach ($periodes as $periode) {
                $tperiodes[] = $periode;
            }
        }
        $projetPeriodes = [];
        foreach ($this->dataUserSession->getDiplomes() as $diplome) {
            $periodes = $projetPeriodeRepository->findByDiplome($diplome, $diplome->getAnneeUniversitaire());
            foreach ($periodes as $periode) {
                $projetPeriodes[] = $periode;
            }
        }

        return $this->render(
            'administration/index.html.twig',
            [
                'stagePeriodes' => $tperiodes,
                'projetPeriodes' => $projetPeriodes,
            ]
        );
    }
}

src/Controller/administration/AbsenceAppelSuiviController.php
<?php
/*
 * Copyright (c) 2021. | David Annebicque | IUT de Troyes  - All Rights Reserved
 * @file /Users/davidannebicque/htdocs/intranetV3/src/Controller/administration/AbsenceAppelSuiviController.php
 * @author davidannebicque
 * @project intranetV3
 * @lastUpdate 23/10/2021 09:44
 */

namespace App\Controller\administration;

use App\Classes\Absences\AbsenceEtatAppel;
use App\Classes\Edt\EdtManager;
use App\Classes\Matieres\TypeMatiereManager;
use App\Components\Exporter\ExporterManager;
use App\Components\Exporter\SourceIterator\DoctrineSourceIterator;
use App\Components\Exporter\SourceIterator\DtoSourceIterator;
use App\Controller\BaseController;
use App\Entity\Date;
use App\Entity\Semestre;
use App\Table\AppelSuiviTableType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/administration/absence/appel')]
class AbsenceAppelSuiviController extends BaseController
{
    private EdtManager $edtManager;
    private AbsenceEtatAppel $absenceEtatAppel;

    public function __construct(EdtManager $edtManager, AbsenceEtatAppel $absenceEtatAppel)
    {
        $this->edtManager = $edtManager;
        $this->absenceEtatAppel = $absenceEtatAppel;
    }

    #[Route('/{semestre}', name: 'administration_absence_appel_index', requirements: ['semestre' => "\d+"])]
    public function index(
        Request $request,
        TypeMatiereManager $typeMatiereManager,
        Semestre $semestre
    ): Response {
        $this->denyAccessUnlessGranted('MINIMAL_ROLE_ABS', $semestre);

        $statsAppel = $this->absenceEtatAppel->getBySemestre($semestre);
        $matieres = $typeMatiereManager->findBySemestreArray($semestre);

        $table = $this->createTable(AppelSuiviTableType::class, [
            'matieres' => $matieres,
            'statsAppel' => $statsAppel,
            'semestre' => $semestre,
        ]);

        $table->handleRequest($request);

        if ($table->isCallback()) {
            return $table->getCallbackResponse();
        }

        return $this->render('administration/absence_appel/index.html.twig',
            [
                'pl' => $this->edtManager->getPlanningSemestre($semestre),
                'semestre' => $semestre,
                'table' => $table,
                'statsAppel' => $statsAppel,
                'matieres' => $matieres,
            ]);
    }

    #[Route('/export/{semestre}.{_format}', name: 'administration_absence_appel_export')]
    public function export(
        ExporterManager $exporterManager,
        Semestre $semestre,
        string $_format
    ) {
        $this->denyAccessUnlessGranted('MINIMAL_ROLE_ABS', $semestre);
        //todo: gérer l'export passer par un DTO, et l'injecter aussi dans le table de l'index
        $statsAppel = $this->absenceEtatAppel->getBySemestre($semestre);
        $datas = new DtoSourceIterator($statsAppel, AbsenceEtatAppel::class);

        return $exporterManager->export($datas, $_format, 'dates');
    }
}

src/Controller/administration/ActualiteController.php
<?php
/*
 * Copyright (c) 2021. | David Annebicque | IUT de Troyes  - All Rights Reserved
 * @file /Users/davidannebicque/htdocs/intranetV3/src/Controller/administration/ActualiteController.php
 * @author davidannebicque
 * @project intranetV3
 * @lastUpdate 09/10/2021 10:02
 */

namespace App\Controller\administration;

use App\Classes\MyExport;
use App\Controller\BaseController;
use App\Entity\Actualite;
use App\Entity\Constantes;
use App\Form\ActualiteType;
use App\Repository\ActualiteRepository;
use App\Table\ActualiteTableType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/administration/actualites', name: 'administration_actualite_')]
class ActualiteController extends BaseController
{
    #[Route('/', name: 'index', options: ['expose' => true], methods: ['GET', 'POST'])]
    public function index(
        Request $request
    ): Response {
        $this->denyAccessUnlessGranted('MINIMAL_ROLE_ASS', $this->getDepartement());

        $table = $this->createTable(ActualiteTableType::class, [
            'departement' => $this->getDepartement(),
        ]);
        $table->handleRequest($request);

        if ($table->isCallback()) {
            return $table->getCallbackResponse();
        }

        return $this->render(
            'administration/actualite/index.html.twig',
            [
                'table' => $table,
            ]
        );
    }

    #[Route('/export.{_format}', name: 'export', requirements: ['_format' => 'csv|xlsx|pdf'], methods: ['GET'])]
    public function export(MyExport $myExport, ActualiteRepository $actualiteRepository, $_format): Response
    {
        $this->denyAccessUnlessGranted('MINIMAL_ROLE_ASS', $this->getDepartement());

        $actualites = $actualiteRepository->getByDepartement($this->getDepartement());

        return $myExport->genereFichierGenerique(
            $_format,
            $actualites,
            'actualites',
            ['actualite_administration', 'utilisateur'],
            ['titre', 'texte', 'departement' => ['libelle']]
        );
    }

    #[Route('/new', name: 'new', methods: ['GET', 'POST'])]
    public function create(Request $request): Response
    {
        $this->denyAccessUnlessGranted('MINIMAL_ROLE_ASS', $this->getDepartement());

        $actualite = new Actualite($this->dataUserSession->getDepartement());
        $form = $this->createForm(ActualiteType::class, $actualite, [
            'attr' => [
                'data-provide' => 'validation',
                'novalidate' => true,
            ],
        ]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->entityManager->persist($actualite);
            $this->entityManager->flush();
            $this->addFlashBag(Constantes::FLASHBAG_SUCCESS, 'actualite.add.success.flash');

            return $this->redirectToRoute('administration_actualite_index');
        }

        return $this->render('administration/actualite/new.html.twig', [
            'actualite' => $actualite,
            'form' => $form->createView(),
        ]);
    }

    #[Route('/{id}', name: 'show', methods: ['GET'])]
    public function show(Actualite $actualite): Response
    {
        $this->denyAccessUnlessGranted('MINIMAL_ROLE_ASS', $actualite->getDepartement());

        return $this->render('administration/actualite/show.html.twig', ['actualite' => $actualite]);
    }

    #[Route('/{id}/edit', name: 'edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Actualite $actualite): Response
    {
        $this->denyAccessUnlessGranted('MINIMAL_ROLE_ASS', $actualite->getDepartement());

        $form = $this->createForm(ActualiteType::class, $actualite, [
            'attr' => [
                'data-provide' => 'validation',
            ],
        ]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->entityManager->flush();
            $this->addFlashBag(Constantes::FLASHBAG_SUCCESS, 'actualite.edit.success.flash');

            if (null !== $request->request->get('btn_update')) {
                return $this->redirectToRoute('administration_actualite_index');
            }

            return $this->redirectToRoute('administration_actualite_edit', ['id' => $actualite->getId()]);
        }

        return $this->render('administration/actualite/edit.html.twig', [
            'actualite' => $actualite,
            'form' => $form->createView(),
        ]);
    }

    #[Route('/{id}', name: 'delete', methods: ['DELETE'])]
    public function delete(Request $request, Actualite $actualite): Response
    {
        $this->denyAccessUnlessGranted('MINIMAL_ROLE_ASS', $actualite->getDepartement());

        $id = $actualite->getId();
        if ($this->isCsrfTokenValid('delete' . $id, $request->request->get('_token'))) {
            $this->entityManager->remove($actualite);
            $this->entityManager->flush();
            $this->addFlashBag(
                Constantes::FLASHBAG_SUCCESS,
                'actualite.delete.success.flash'
            );

            return $this->json($id, Response::HTTP_OK);
        }

        $this->addFlashBag(Constantes::FLASHBAG_ERROR, 'actualite.delete.error.flash');

        return $this->json(false, Response::HTTP_INTERNAL_SERVER_ERROR);
    }

    #[Route('/{id}/duplicate', name: 'duplicate', methods: ['GET', 'POST'])]
    public function duplicate(Actualite $actualite): Response
    {
        $this->denyAccessUnlessGranted('MINIMAL_ROLE_ASS', $actualite->getDepartement());

        $newActualite = clone $actualite;

        $this->entityManager->persist($newActualite);
        $this->entityManager->flush();
        $this->addFlashBag(Constantes::FLASHBAG_SUCCESS, 'actualite.duplicate.success.flash');

        return $this->redirectToRoute('administration_actualite_edit', ['id' => $newActualite->getId()]);
    }
}

src/Controller/administration/AffecterEnseignantsGroupesController.php
<?php
/*
 * Copyright (c) 2021. | David Annebicque | IUT de Troyes  - All Rights Reserved
 * @file /Users/davidannebicque/htdocs/intranetV3/src/Controller/administration/AffecterEnseignantsGroupesController.php
 * @author davidannebicque
 * @project intranetV3
 * @lastUpdate 07/10/2021 09:45
 */

namespace App\Controller\administration;

use App\Controller\BaseController;
use App\Entity\Semestre;
use Exception;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class AffecterEnseignantsGroupesController.
 *
 * @Route("/administration/affecter-enseignants-groupes")
 */
class AffecterEnseignantsGroupesController extends BaseController
{
    /**
     * @Route("/{semestre}", name="administration_affecter_enseignant_groupe_index", methods="GET|POST")
     *
     * @throws Exception
     */
    public function index(
        Semestre $semestre
    ): Response {
        $this->denyAccessUnlessGranted('MINIMAL_ROLE_ASS', $semestre);

        return $this->render('administration/affecterEnseignantsGroupes/index.html.twig', [
            'semestre' => $semestre,
        ]);
    }
}

templates/administration/edtCompare/_plusInfo.html.twig
<table class="table table-striped">
    <thead>
    <tr>
        <td>Date</td>
        <td>Heure</td>
        <td>Enseignant</td>
        <td>Type</td>
        <td>Groupe</td>
    </tr>
    </thead>
    <tbody>
    {% for pl in planning %}
        <tr>
            <td>{{ pl.date|format_date('short') }}</td>
            <td>{{ pl.debutTexte }} | {{ pl.finTexte }}</td>
            {% if pl.intervenant != null %}
                <td>{{ pl.intervenant.displayPr }}</td>
            {% else %}
                <td> -</td>
            {% endif %}
            <td>{{ pl.type|upper }}</td>
            {% if pl.groupe != null %}
                <td>{{ pl.displayGroupe }}</td>
            {% else %}
                <td> -</td>
            {% endif %}
        </tr>
    {% endfor %}
    </tbody>
</table>

templates/administration/edtCompare/compareMatieres.html.twig
{% extends 'base.html.twig' %}

{% block header %}
    {{ 'adm.edt.compare.matieres.heading'|trans }}
{% endblock %}

{% block headeractions %}
    <div class="header-action">
        <div class="buttons">
            <a href="{{ path('administration_edt_compare_personnels', {source:source}) }}"
               class="btn btn-info btn-float btn-sm"
               data-bs-toggle="tooltip"
               data-bs-placement="bottom"
               title="{{ 'atitle.comparer_par_personnels'|trans }}">
                <i class="fas fa-random"></i></a>
            <a href="{{ path('administration_edt_index') }}"
               class="btn btn-primary btn-float"
               data-bs-toggle="tooltip"
               data-bs-placement="bottom"
               title="{{ 'atitle.retour_administration'|trans }}">
                <i class="fas fa-arrow-left"></i></a>
            <a href="{{ path('administration_index') }}"
               class="btn btn-primary btn-float"
               data-bs-toggle="tooltip"
               data-bs-placement="bottom"
               title="{{ 'atitle.retour_administration'|trans }}">
                <i class="{{ iconAdmin }}"><span class="sr-only">Administration</span></i></a>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="card">
        <h4 class="card-title"><strong>{{ 'adm.edt.compare.matieres.heading'|trans }}</strong></h4>
        <div class="card-body">
            <ul class="nav nav-tabs">
                {% for semestre in user_data.semestres %}
                    <li class="nav-item {% if loop.first %} active{% endif %}">
                        <a href="#semestre_{{ semestre.id }}"
                           class="nav-link {% if loop.first %} active{% endif %}"
                           data-bs-toggle="tab">{{ semestre.display }}</a>
                    </li>
                {% endfor %}
            </ul>
            <div class="tab-content padding">
                {% for semestre in user_data.semestres %}
                    <div class="tab-pane {% if loop.first %} active {% endif %}"
                         id="semestre_{{ semestre.id }}">
                        <h2>Modules du semestre {{ semestre.display }}</h2>
                        <table class="table table-hover">
                            <thead>
                                    <tr>
                                        <th colspan>Enseignant</th>
                                        <th colspan="2" class="text-center">CM</th>
                                        <th colspan="2" class="text-center">TD</th>
                                        <th colspan="2" class="text-center">TP</th>
                                        <th>&nbsp;</th>
                                    </tr>
                                    </thead>
                            {% for matiere in matieres|filter(matiere => matiere.semestre.id == semestre.id) %}
                                <tr style="background-color:#cccccc;">
                                    <td colspan="10" style="text-align:center;">
                                        <button
                                                {{ stimulus_controller('modal', {
                                                    size: 'lg',
                                                    modalTitle: 'compare.plusinfos.details.title'|trans,
                                                    modalUrl: path('administration_edt_compare_plus_info',
                                                        {'matiere': matiere.typeIdMatiere}) })}}
                                                data-action="click->modal#openModal"
                                                class="btn btn-info"
                                                data-size="lg"
                                                data-bs-toggle="tooltip"
                                                data-bs-placement="bottom"
                                                title="{{ 'compare.plusinfos.details'|trans }}"
                                        >
                                            <i class="{{ iconShow }}"></i> {{ matiere.display }}
                                        </button>


                                    </td>
                                </tr>
                                <tr>
                                    <td>Intervenant</td>
                                    <td>EDT</td>
                                    <td>Prévi.</td>
                                    <td>EDT</td>
                                            <td>Prévi.</td>
                                            <td>EDT</td>
                                            <td>Prévi.</td>
                                        </tr>
                                {% for ed in comparatifs[matiere.typeIdMatiere] %}
                                    <tr>
                                        <td>{{ ed.personnel_prenom }} {{ ed.personnel_nom }}</td>
                                        <td>
                                                    <span class="badge rounded-pill {% if ed.nbCMEDT > ed.nbCMPrevi %}
                                                    bg-danger {% elseif ed.nbCMEDT == ed.nbCMPrevi %} bg-success {% else %} bg-warning {% endif %}">{{ ed.nbCMEDT }}</span>
                                        </td><!--CM -->
                                        <td>
                                            <span class="badge rounded-pill {% if ed.nbCMPrevi > ed.nbCMEDT %} bg-danger {% elseif ed.nbCMEDT == ed.nbCMPrevi %} bg-success {% else %} bg-warning {% endif %}">{{ ed.nbCMPrevi }}</span>
                                        </td>
                                        <td>
                                            <span class="badge rounded-pill {% if ed.nbTDEDT > ed.nbTDPrevi %} bg-danger {% elseif ed.nbTDEDT == ed.nbTDPrevi %} bg-success {% else %} bg-warning {% endif %}">{{ ed.nbTDEDT }}</span>
                                        </td><!--TD -->
                                        <td>
                                            <span class="badge rounded-pill {% if ed.nbTDPrevi > ed.nbTDEDT %} bg-danger {% elseif ed.nbTDEDT == ed.nbTDPrevi %} bg-success {% else %} bg-warning {% endif %}">{{ ed.nbTDPrevi }}</span>
                                        </td>
                                        <td>
                                            <span class="badge rounded-pill {% if ed.nbTPEDT > ed.nbTPPrevi %} bg-danger {% elseif ed.nbTPEDT == ed.nbTPPrevi %} bg-success {% else %} bg-warning {% endif %}">{{ ed.nbTPEDT }}</span>
                                        </td><!-- TP -->
                                        <td>
                                            <span class="badge rounded-pill {% if ed.nbTPPrevi > ed.nbTPEDT %} bg-danger {% elseif ed.nbTPEDT == ed.nbTPPrevi %} bg-success {% else %} bg-warning {% endif %}">{{ ed.nbTPPrevi }}</span>
                                        </td>
                                        <td></td>
                                    </tr>
                                {% endfor %}
                                    {% endfor %}
                                </table>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
{% endblock %}

templates/administration/edtCompare/comparePersonnel.html.twig
{% extends 'base.html.twig' %}

{% block header %}
    {{ 'adm.edt.compare.personnels.heading'|trans }}
{% endblock %}

{% block headeractions %}
    <div class="header-action">
        <div class="buttons">
            <a href="{{ path('administration_edt_compare_matiere', {source:source}) }}"
               class="btn btn-info btn-float btn-sm"
               data-bs-toggle="tooltip"
               data-bs-placement="bottom"
               title="{{ 'atitle.comparer_par_matiere'|trans }}">
                <i class="fas fa-random"></i></a>
            <a href="{{ path('administration_edt_index') }}"
               class="btn btn-primary btn-float"
               data-bs-toggle="tooltip"
               data-bs-placement="bottom"
               title="{{ 'atitle.retour_administration'|trans }}">
                <i class="fas fa-arrow-left"></i></a>
            <a href="{{ path('administration_index') }}"
               class="btn btn-primary btn-float"
               data-bs-toggle="tooltip"
               data-bs-placement="bottom"
               title="{{ 'atitle.retour_administration'|trans }}">
                <i class="{{ iconAdmin }}"><span class="sr-only">Administration</span></i></a>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="card">
        <h4 class="card-title"><strong>{{ 'adm.edt.compare.personnels.heading'|trans }}</strong></h4>
        <div class="card-body">

            <table class="table table-hover">
                <thead>
                <tr>
                    <th>Matière</th>
                    <th>Semestre</th>
                    <th colspan="2" class="text-center">CM</th>
                    <th colspan="2" class="text-center">TD</th>
                    <th colspan="2" class="text-center">TP</th>
                    <th>&nbsp;</th>
                </tr>
                </thead>
                {% for personnel in personnels|filter(personnel => personnel.typeuser != 'ASS' and personnel.typeuser!='TEC') %}
                    <tr style="background-color:#cccccc;">
                        <td colspan="10"
                            style="text-align:center;">{{ personnel.display }}</td>
                    </tr>
                    <tr>
                        <td>&nbsp;</td>
                        <td>Semestre</td>
                        <td>EDT.</td>
                        <td>Prévi.</td>
                        <td>EDT</td>
                        <td>Prévi.</td>
                        <td>EDT</td>
                        <td>Prévi.</td>
                    </tr>
                    {% for ed in comparatifs[personnel.id] %}
                        <tr>
                            <td>
                                <button
                                        {{ stimulus_controller('modal', {
                                            size: 'lg',
                                            modalTitle: 'compare.plusinfos.details.title'|trans,
                                            modalUrl:  path('administration_edt_compare_plus_info',
                                                {'matiere': ed.matiere_id}) })}}
                                        data-action="click->modal#openModal"
                                        class="btn btn-info"
                                        data-bs-toggle="tooltip"
                                        data-bs-placement="bottom"
                                        title="{{ 'compare.plusinfos.details'|trans }}"
                                >
                                    <i class="{{ iconShow }}"></i> {{ ed.matiere_code }} | {{ ed.matiere_libelle }}
                                </button>
                            <td>{{ ed.semestre_libelle }}</td>
                            <td>
                                <span class="badge rounded-pill {% if ed.nbCMEDT > ed.nbCMPrevi %} bg-danger {% elseif ed.nbCMEDT == ed.nbCMPrevi %} bg-success {% else %} bg-warning {% endif %}">{{ ed.nbCMEDT }}</span>
                            </td><!--CM -->
                            <td>
                                <span class="badge rounded-pill {% if ed.nbCMPrevi > ed.nbCMEDT %} bg-danger {% elseif ed.nbCMEDT == ed.nbCMPrevi %} bg-success {% else %} bg-warning {% endif %}">{{ ed.nbCMPrevi }}</span>
                            </td>

                            <td>
                                <span class="badge rounded-pill {% if ed.nbTDEDT > ed.nbTDPrevi %} bg-danger {% elseif ed.nbTDEDT == ed.nbTDPrevi %} bg-success {% else %} bg-warning {% endif %}">{{ ed.nbTDEDT }}</span>
                            </td><!--TD -->
                            <td>
                                <span class="badge rounded-pill {% if ed.nbTDPrevi > ed.nbTDEDT %} bg-danger {% elseif ed.nbTDEDT == ed.nbTDPrevi %} bg-success {% else %} bg-warning {% endif %}">{{ ed.nbTDPrevi }}</span>
                            </td>

                            <td>
                                <span class="badge rounded-pill {% if ed.nbTPEDT > ed.nbTPPrevi %} bg-danger {% elseif
                                    ed.nbTPEDT == ed.nbTPPrevi %} bg-success {% else %} bg-warning {% endif %}">{{ ed.nbTPEDT }}</span>
                            </td><!-- TP -->
                            <td>
                                <span class="badge rounded-pill {% if ed.nbTPPrevi > ed.nbTPEDT %} bg-danger {% elseif ed.nbTPEDT == ed.nbTPPrevi %} bg-success {% else %} bg-warning {% endif %}">{{ ed.nbTPPrevi }}</span>
                            </td>

                        </tr>
                    {% endfor %}
                {% endfor %}
            </table>
        </div>
    </div>


    <div id="modalcompare" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
         aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div id="zone_modal_edt">
                    test
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
{% endblock %}